'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CapaPresentacion.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eye_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eye_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_100px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_100px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_activity_history_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_activity_history_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_add_file_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_add_file_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_add_user_group_man_man_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_add_user_group_man_man_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_alarms_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_alarms_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_alarms_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_alarms_641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_basket_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_basket_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_booking_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_booking_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_booking_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_booking_641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_bookmark_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_bookmark_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_box_important_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_box_important_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_bulleted_list_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_bulleted_list_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_businessman_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_businessman_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_calendar_30_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_calendar_30_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_camera_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_camera_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_camera_blanco_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_camera_blanco_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_cancel_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_cancel_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_cloud_sync_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_cloud_sync_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_data_transfer_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_data_transfer_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_database_view_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_database_view_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_database_white_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_database_white_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_delete_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_delete_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_delete_bin_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_delete_bin_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_delete_bin_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_delete_bin_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_delete_bin_322() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_delete_bin_322", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_delete_user_male_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_delete_user_male_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_document_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_document_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_download_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_download_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_download_resume_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_download_resume_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_duplicate_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_duplicate_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_edit_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_edit_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_email_send_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_email_send_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_error_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_error_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_exit_black_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_exit_black_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_eye_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_eye_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_gmail_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_gmail_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_handcart_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_handcart_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_increase_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_increase_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_joyent_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_joyent_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_list_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_list_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_logout_rounded_left_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_logout_rounded_left_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_logout_rounded_left_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_logout_rounded_left_641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_maintenance_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_maintenance_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_maintenance_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_maintenance_641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_maintenance_642() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_maintenance_642", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_meeting_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_meeting_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_microsoft_excel_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_microsoft_excel_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_microsoft_excel_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_microsoft_excel_641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_more_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_more_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_museum_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_museum_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_ok_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_ok_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_ok_green_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_ok_green_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_opened_folder_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_opened_folder_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_order_history_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_order_history_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_pdf_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_pdf_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_pencil_white_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_pencil_white_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_picture_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_picture_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_protect_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_protect_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_raspberry_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_raspberry_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_save_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_save_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_save_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_save_641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_search_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_search_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_search_more_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_search_more_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_secured_file_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_secured_file_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_send_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_send_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_settings_balck_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_settings_balck_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_storage_box_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_storage_box_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_trash_can_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_trash_can_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_trolley_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_trolley_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_unavailable_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_unavailable_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_update_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_update_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_update_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_update_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_update_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_update_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_upload_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_upload_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_user_account_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_user_account_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_user_folder_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_user_folder_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_waiter_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_waiter_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_warning_shield_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_warning_shield_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_warning_shield_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_warning_shield_641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_website_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_website_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_writer_male_black_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_writer_male_black_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_sena_blanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_sena_blanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logoSenaradial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoSenaradial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property microsoft_excel_100px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("microsoft_excel_100px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property return_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("return_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
